# Generated by Django 5.1.7 on 2025-03-28 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_historicalsite_is_active_historicalsite_location_and_more'),
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.site'),
        ),
        migrations.AddField(
            model_name='incident',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='base.site'),
        ),
    ]
