# Generated by Django 5.1.7 on 2025-03-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_historicalincident_site_incident_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalincident',
            name='location',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='location',
        ),
    ]
