# Generated by Django 5.1.7 on 2025-04-02 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_emplacement'),
        ('incident', '0003_remove_historicalincident_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='emplacement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.emplacement', verbose_name='Emplacement spécifique'),
        ),
        migrations.AddField(
            model_name='incident',
            name='emplacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='base.emplacement', verbose_name='Emplacement spécifique'),
        ),
    ]
