# Generated by Django 5.1.7 on 2025-04-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_historicalincident_emplacement_incident_emplacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalincident',
            name='type',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='type',
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='action_correction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='blessure_potentielle',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='cause_principale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='commentaire_correction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='consequence_ose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='consequence_pa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='photo_correction',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='solution_ose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='solution_pa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='type_incident',
            field=models.CharField(blank=True, choices=[('PA', 'PA'), ('OSE', 'OSE')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='action_correction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='blessure_potentielle',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='cause_principale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='commentaire_correction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='consequence_ose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='consequence_pa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='photo_correction',
            field=models.ImageField(blank=True, null=True, upload_to='corrections/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='solution_ose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='solution_pa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='type_incident',
            field=models.CharField(blank=True, choices=[('PA', 'PA'), ('OSE', 'OSE')], max_length=3, null=True),
        ),
    ]
