# Generated by Django 5.1.7 on 2025-04-07 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0005_remove_historicalincident_type_remove_incident_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalincident',
            name='criticity',
            field=models.CharField(blank=True, choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='incident.incidentcategory'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='criticity',
            field=models.CharField(blank=True, choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée')], max_length=50, null=True),
        ),
    ]
