# Generated by Django 5.1.7 on 2025-04-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_historicalincident_location_incident_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalincident',
            name='category',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalincident',
            name='criticity',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='criticity',
        ),
        migrations.AlterField(
            model_name='incident',
            name='photo_correction',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.DeleteModel(
            name='IncidentCategory',
        ),
    ]
