# Generated by Django 5.1.7 on 2025-03-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='site',
        ),
        migrations.RemoveField(
            model_name='user',
            name='site',
        ),
    ]
