# Generated by Django 5.1.7 on 2025-03-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_notification_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_helpdesk',
            field=models.BooleanField(blank=True, default=False, help_text="Cocher si l'utilisateur fait partie de l'équipe helpdesk.", verbose_name='Support technique ?'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_manager',
            field=models.BooleanField(blank=True, default=False, help_text="Cocher si l'utilisateur a des droits de gestion.", verbose_name='Gestionnaire ?'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_member',
            field=models.BooleanField(blank=True, default=False, help_text="Cocher si l'utilisateur a un accès basique (membre par défaut).", verbose_name='Utilisateur standard ?'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_helpdesk',
            field=models.BooleanField(blank=True, default=False, help_text="Cocher si l'utilisateur fait partie de l'équipe helpdesk.", verbose_name='Support technique ?'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(blank=True, default=False, help_text="Cocher si l'utilisateur a des droits de gestion.", verbose_name='Gestionnaire ?'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(blank=True, default=False, help_text="Cocher si l'utilisateur a un accès basique (membre par défaut).", verbose_name='Utilisateur standard ?'),
        ),
    ]
