# Generated by Django 5.1.7 on 2025-03-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_historicaluser_is_helpdesk_historicaluser_is_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_helpdesk',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_member',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_helpdesk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_member',
        ),
    ]
