# Generated by Django 5.1.7 on 2025-03-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_historicaluser_is_helpdesk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='qr_code_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='qr_code_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
