# Generated by Django 5.1.7 on 2025-04-02 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_historicalsite_is_active_historicalsite_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'emplacement")),
                ('description', models.TextField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplacements', to='base.site')),
            ],
            options={
                'verbose_name': 'Emplacement de travail',
                'verbose_name_plural': 'Emplacements de travail',
                'ordering': ['site', 'name'],
            },
        ),
    ]
