# Generated by Django 5.1.7 on 2025-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='date_awarded',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'attribution"),
        ),
    ]
