# Generated by Django 5.1.7 on 2025-03-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_alter_bonus_date_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='bonus_type',
            field=models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel')], max_length=20, verbose_name='frequence'),
        ),
    ]
