# Generated by Django 5.1.7 on 2025-03-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_historicalsite_is_active_historicalsite_location_and_more'),
        ('reward', '0003_alter_bonus_bonus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_sites',
            field=models.ManyToManyField(blank=True, null=True, related_name='authorized_users', to='base.site'),
        ),
    ]
